In [1]:
# Load all libraries
import rasterio
import numpy as np
import pandas as pd
import os
from collections import Counter
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Create the column names of dataframe from indices' names
colNames = []
folder = 'masked_CC'
i = 0
for subfolder in os.listdir(folder):
    for filename in os.listdir(os.path.join(folder, subfolder)):
        img_name = filename.split('_')[1]
        colNames.append(img_name)
    i += 1
    if i > 0:
        break

In [3]:
colNames

['blue',
 'dbsi',
 'evi',
 'gi',
 'gndvi',
 'green',
 'kndvi',
 'ndci',
 'ndpi',
 'ndvigb',
 'ndvi',
 'nir',
 'npci',
 'psri',
 'red',
 'rvi1',
 'rvi2',
 'sipi',
 'srpi',
 'tvi',
 'vari',
 'VH',
 'VV-VH',
 'VV']

In [4]:
colNames.append('class')

In [5]:
colNames

['blue',
 'dbsi',
 'evi',
 'gi',
 'gndvi',
 'green',
 'kndvi',
 'ndci',
 'ndpi',
 'ndvigb',
 'ndvi',
 'nir',
 'npci',
 'psri',
 'red',
 'rvi1',
 'rvi2',
 'sipi',
 'srpi',
 'tvi',
 'vari',
 'VH',
 'VV-VH',
 'VV',
 'class']

In [6]:
df = pd.DataFrame(columns = colNames)

In [7]:
df

Empty DataFrame
Columns: [blue, dbsi, evi, gi, gndvi, green, kndvi, ndci, ndpi, ndvigb, ndvi, nir, npci, psri, red, rvi1, rvi2, sipi, srpi, tvi, vari, VH, VV-VH, VV, class]
Index: []

[0 rows x 25 columns]

In [8]:
# Get the values of images in one dataframe, excluding from it zero class
subfolder = '2023-09-10'
x = len([name for name in os.listdir(os.path.join(folder, subfolder)) if os.path.isfile(os.path.join(folder, subfolder, name))])
i = 0
array = {}
for filename in os.listdir(os.path.join(folder, subfolder)):
    if i < x:
        img = rasterio.open(os.path.join(folder, subfolder, filename))
        array[f'var{i}'] = img.read()
        i += 1
imgy =  rasterio.open('images/CC_2023/vector_2023.tif')
array[f'var{i+1}'] = imgy.read()
arra = np.concatenate(list(array.values()),0)
df_img = pd.DataFrame(arra.reshape([x+1,-1]).T, columns=colNames)
df_filtered = df_img[df_img['class'] > 0]
df = pd.concat([df, df_filtered])

In [22]:
df

,blue,dbsi,evi,gi,gndvi,green,kndvi,ndci,ndpi,ndvigb,...,rvi1,rvi2,sipi,srpi,tvi,vari,VH,VV-VH,VV,class
1328,884.0,0.332088,0.299619,0.633595,0.408799,1290.0,0.041239,0.085766,0.535219,0.186753,...,1.509823,2.382946,0.553310,0.434185,32440.0,-0.305487,0.015961,4.992914,0.079693,2.0
1329,900.0,0.313104,0.316513,0.655674,0.402827,1352.0,0.045201,0.110632,0.525780,0.200710,...,1.540252,2.349112,0.558391,0.436469,38440.0,-0.282418,0.013790,6.609541,0.091145,2.0
1330,921.0,0.308188,0.321067,0.654215,0.404793,1366.0,0.045702,0.104439,0.522043,0.194578,...,1.544061,2.360176,0.555609,0.441092,39280.0,-0.285038,0.014154,7.793242,0.110306,2.0
1331,924.0,0.314756,0.288697,0.646140,0.397342,1406.0,0.039744,0.105815,0.514167,0.206867,...,1.498162,2.318634,0.558317,0.424632,34240.0,-0.289691,0.011056,9.924413,0.109723,2.0
1332,934.0,0.307736,0.292751,0.638164,0.405949,1418.0,0.041307,0.095461,0.511034,0.205782,...,1.510351,2.366714,0.564569,0.420342,35880.0,-0.297118,0.009376,8.233112,0.077192,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12688818,133.0,-0.112032,1.604169,0.842697,0.820036,300.0,0.553944,0.341351,0.677939,0.385681,...,8.522472,10.113333,0.916009,0.373596,158440.0,-0.107075,0.006991,12.851355,0.089838,1.0
12688819,83.0,-0.216794,1.547764,1.206587,0.771477,403.0,0.572320,0.369216,0.590031,0.658436,...,9.353293,7.751861,0.948238,0.248503,170160.0,0.105505,0.008894,7.023579,0.062466,1.0
12691957,464.0,-0.126076,1.130570,0.912941,0.576650,776.0,0.289042,0.067982,0.419379,0.251613,...,3.400000,3.724227,0.723315,0.545882,119440.0,-0.063683,0.037745,3.088385,0.116571,1.0
12691958,108.0,-0.082661,1.354236,0.929268,0.763867,381.0,0.507784,0.407514,0.665496,0.558282,...,6.941463,7.469816,0.926879,0.263415,145000.0,-0.042460,0.027237,3.846247,0.104760,1.0
12691959,149.0,-0.165537,1.517407,1.055138,0.753007,421.0,0.525782,0.263158,0.598857,0.477193,...,7.488722,7.097387,0.905005,0.373434,156220.0,0.032787,0.018375,3.187778,0.058575,1.0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70836 entries, 1328 to 12691959
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   blue    70836 non-null  float64
 1   dbsi    70836 non-null  float64
 2   evi     70836 non-null  float64
 3   gi      70836 non-null  float64
 4   gndvi   70836 non-null  float64
 5   green   70836 non-null  float64
 6   kndvi   70836 non-null  float64
 7   ndci    70836 non-null  float64
 8   ndpi    70836 non-null  float64
 9   ndvigb  70836 non-null  float64
 10  ndvi    70836 non-null  float64
 11  nir     70836 non-null  float64
 12  npci    70836 non-null  float64
 13  psri    70836 non-null  float64
 14  red     70836 non-null  float64
 15  rvi1    70836 non-null  float64
 16  rvi2    70836 non-null  float64
 17  sipi    70836 non-null  float64
 18  srpi    70836 non-null  float64
 19  tvi     70836 non-null  float64
 20  vari    70836 non-null  float64
 21  VH      70836 non-null  float64
 22  VV-VH   70836 non-null  float64
 23  VV      70836 non-null  float64
 24  class   70836 non-null  float64
dtypes: float64(25)
memory usage: 14.1 MB

In [24]:
df.describe()

,blue,dbsi,evi,gi,gndvi,green,kndvi,ndci,ndpi,ndvigb,...,rvi1,rvi2,sipi,srpi,tvi,vari,VH,VV-VH,VV,class
count,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000,...,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000,70836.000000
mean,376.800144,-0.079805,1.085273,1.084761,0.588863,775.785843,0.341430,0.313526,0.485703,0.429762,...,5.656533,4.601375,0.776235,0.401815,127811.243718,0.003181,0.018969,8.146039,0.094902,1.618781
std,306.398753,0.226814,0.541669,0.375716,0.149461,348.908909,0.215045,0.174083,0.083991,0.192829,...,4.548222,2.220480,0.161120,0.108363,69765.553902,0.197747,0.011440,82.474607,0.113980,0.485690
min,1.000000,-0.523478,0.051656,0.410138,0.067774,89.000000,0.001156,-0.182738,0.022573,0.033264,...,1.070393,1.145403,0.166746,0.003401,-10320.000000,-0.463687,0.000014,0.176180,0.002988,1.000000
25%,162.000000,-0.279186,0.562421,0.765349,0.452439,545.000000,0.110111,0.152403,0.429531,0.244340,...,1.996276,2.652562,0.623230,0.344523,66255.000000,-0.181062,0.010855,2.790756,0.051536,1.000000
50%,260.000000,-0.123635,1.162943,1.003804,0.624213,672.000000,0.379781,0.327955,0.479701,0.431676,...,4.439227,4.322160,0.833697,0.419053,132000.000000,0.002395,0.016692,4.578459,0.075628,2.000000
75%,522.000000,0.123457,1.544538,1.321101,0.709402,914.000000,0.535368,0.455546,0.537425,0.562232,...,7.813347,5.882353,0.908715,0.472434,188080.000000,0.164676,0.024456,7.799378,0.110582,2.000000
max,2152.000000,0.652618,3.448349,4.183908,0.931488,2834.000000,0.738412,0.826261,0.896451,0.995546,...,73.428571,28.191781,0.999501,1.620690,372760.000000,0.893548,0.147113,16510.246094,5.831423,2.000000

In [12]:
df['class'].value_counts()

2.0    67308
1.0    40668
Name: class, dtype: int64

In [13]:
# Check for infinity values
np.isinf(df).values.sum()

363

In [14]:
# Check at which column the infinity values are
df.columns.to_series()[np.isinf(df).any()]

gi        gi
rvi1    rvi1
srpi    srpi
dtype: object

In [15]:
# Replacing infinite with nan
df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [16]:
df.isnull().sum()

blue        0
dbsi        0
evi         0
gi        181
gndvi       0
green       0
kndvi       0
ndci        0
ndpi        0
ndvigb      0
ndvi        0
nir         0
npci      180
psri        0
red         0
rvi1      181
rvi2        0
sipi        0
srpi      181
tvi         0
vari        0
VH          0
VV-VH       0
VV          0
class       0
dtype: int64

In [17]:
df.drop(df[df['VV'] <= -99999].index, inplace=True)

In [18]:
df.drop(df[df['blue'] == 0].index, inplace=True)

In [19]:
df.drop(df[df['blue'] > 10000].index, inplace=True)

In [20]:
df.dropna(inplace=True)

In [21]:
df['class'].value_counts()

2.0    43832
1.0    27004
Name: class, dtype: int64

In [25]:
# Save the dataframe in csv file
df.to_csv('CC_20230910.csv', index=False)